sequentech/deployment-tool

agora-elections/app.yml, agora-elections/main.yml, agora-elections/packages.yml, doc/complete-deployment.md
Before this change we should run the agora_elections in dev mode and open the browser to create the tables, but with this change all steps are automated.
=> Automated agora_elections database creation

agora-elections/app.yml, agora-elections/packages.yml
I has changed expect by nohup, because the error continue in new installations.
=> Fixed agora-elections expect.

agora-elections/packages.yml, agora-gui/repo.yml, doc/base.playbook.yml, doc/complete-deployment.md
It also adds some extra documentation as a bonus =)
=> Fix deployment expect and https

agora-elections/app.yml, agora-elections/main.yml, agora-elections/packages.yml, agora-elections/templates/application.local.conf
Updated agora elections config file and app.yml to work with the next branch of agora_elections.
In the agora_elections repo we've added two evolutions sql files so the tables now are created automatically.
I've also added the needed memcache settings for the new memcache plugin added to agora_elections.
=> Upaelections

agora-elections/templates/results.req.txt, agora-verifier/build.yml, agora-verifier/main.yml, agora-verifier/packages.yml, agora-verifier/repo.yml, agora-verifier/revert_java8.yml, agora-verifier/user.yml, doc/agora.playbook.yml, doc/auth.playbook.yml, playbook.yml, repos.yml
Added agora-verifier deployment support. To use this branch, you need to change in repo.yml:
- agora-tally branch to openstv
=> Agora verifier deployment support

agora-elections/main.yml, agora-elections/postgres.yml, agora-elections/templates/application.local.conf, agora-elections/templates/nginx.conf, agora-elections/templates/test.local.conf, agora-gui/guiconfig.yml, agora-gui/templates/nginx.conf, agora-tools/templates/eoconf.json, agora-verifier/aguiconfig.yml, authapi/install.yml, authapi/templates/deploy.py, authapi/templates/fixture.json, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel_deployment.md, doc/production/config.auth.yml, doc/production/config.master.yml, oneserver/templates/oneserver.conf, sentry/sentry.yml, sentry/templates/deploy_sentry.py, sentry/templates/sentry.conf.py, system.yml
Depends on PR https://github.com/agoravoting/agora-dev-box/pull/36
=> Group configs

authapi/templates/deploy.py, authapi/templates/fixture.json, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml, sentry/templates/deploy_sentry.py
Note: This PR depends in https://github.com/agoravoting/agora-dev-box/pull/40, process that one first
=> Fix sentry dsn

authapi/templates/deploy.py, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml, doc/production_deployment.md, templates/cert.sh
increses certificates lifetimes and make them configurable. this PR depends on https://github.com/agoravoting/agora-dev-box/pull/42 so do that one first
=> Increse cert lifetime

authapi/templates/deploy.py, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
See https://trello.com/c/PEVzd3jH/504-use-replaces-for-replacing-url-s-and-code-s-instead-of-being-a-template-because-it-s-too-powerful-and-for-example-the-char-makes for details
=> add support for the new templating format for sending auth messages

authapi/install.yml, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml, oneserver/templates/oneserver.conf, sentry/templates/sentry.conf.py
First merge this other PR https://github.com/agoravoting/agora-dev-box/pull/46 More details here: https://trello.com/c/5SKpatsU/518-do-not-execute-psql-on-a-slave-machine
=> Fix slave election start

agora-gui/guiconfig.yml, authapi/install.yml, authapi/templates/fixture.json, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
Note: merge https://github.com/agoravoting/agora-dev-box/pull/56 first
=> Parametrize administrator registration details

agora-elections/main.yml, agora-elections/templates/application.local.conf, agora-elections/templates/nginx.conf, agora-elections/templates/pipes_whitelist, agora-verifier/repo.yml, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
- add support for pipes-whitelist
- add support for maxrevotes configuration
- add support for private_path_verify_ssl_client_certificate to be backwards compatible
=> pipes-whitelist, maxrevotes, backwards compatibility configs

agora-elections/main.yml, agora-elections/templates/application.local.conf, agora-verifier/repo.yml, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml, oneserver/templates/nginx.conf
adding support for max body size
fix agora-elections admin config
=> Fix aelections admin config

agora-gui/templates/avConfig.js, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
Make configurable at deployment which layouts and electoral systems are available as options in the administrative interface
=> Shown question options

authapi/templates/authapi_celery.sh
The -B option launch the worker with the beat to run the periodic tasks.
=> authapi: Launch celery beat with worker

agora-gui/templates/avConfig.js, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
…iguring shown auth methods in admin gui at once
=> adding support for smart-link auth method

authapi/templates/deploy.py, config.yml, doc/devel/agora.config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
=> iadding new config.yml setting to configure the auth token timeout

agora-elections/main.yml, agora-elections/templates/application.local.conf, agora-gui/nginx.yml, agora-gui/repo.yml, agora-tools/main.yml, authapi/install.yml, authapi/user.yml, eorchestra/auth.yml, eorchestra/commands.yml, eorchestra/main.yml, eorchestra/users.yml, oneserver/main.yml, sentry/sentryconf.yml, sentry/supervisor.yml, sentry/user.yml, system.yml
agora-elections configuration file
=> improving some file permissions and setting the application.secret in

agora-elections/templates/run.sh, authapi/templates/deploy.py, authapi/templates/uwsgi.ini, eorchestra/templates/auth.ini, system.yml
* initial work on adding timezone support
* using UTC for logging
* reverting system configuration of timezone - better use UTC always as a policy, as usually recommended
* configuring server UTC always
* unifiying log format for eorchestra too
* fixing yaml
* reverting to UTC and quoting things
* uwsgi quotes
* fixing datetime formatter
* fix logger.xml reference
=> Timezone support

config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel/sequent.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml, iam/templates/deploy.py, iam/templates/test_settings.py, sequent-ui/templates/SequentConfig.js
Include changes from [this PR](https://github.com/sequentech/deployment-tool/pull/302) in version 6.1.x
=> Support HTML format when sending email auth-codes

iam/templates/deploy.py, iam/templates/test_settings.py
- adding OTL_URL configuration in iam test settings
- adding OTL_URL in iam deploy settings
=> adding otl support

iam/templates/deploy.py, iam/templates/test_settings.py
* adding otl support
- adding OTL_URL configuration in iam test settings
- adding OTL_URL in iam deploy settings
* WIP
=> adding otl support (#306)

ballot-box/templates/application.local.conf, config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel/sequent.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
Enable setting the user/pass for each of the trustees for the keys ceremonies.
=> Add keys ceremonies

halb/main.yml, halb/packages.yml, halb/repmgr.yml
[Include changes from master in 7.1.x branch.](https://github.com/sequentech/deployment-tool/pull/311)
=> Improvements to master-slave deployment (#311)

config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel/sequent.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
Parent issue: https://github.com/sequentech/meta/issues/48
=> French language support

eorchestra/templates/nginx.conf
Parent issue: https://github.com/sequentech/meta/issues/94
=> nginx parameters not applied in trustees

eorchestra/templates/nginx.conf
Parent issue: https://github.com/sequentech/meta/issues/94
=> nginx parameters not applied in trustees (#332)

iam/templates/deploy.py, iam/templates/test_settings.py
Parent issue: https://github.com/sequentech/epi/issues/114
=> Alternative Auth methods support

iam/templates/deploy.py, iam/templates/test_settings.py
Parent issue: https://github.com/sequentech/epi/issues/114
=> Alternative Auth methods support (#334)

config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel/sequent.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml, sequent-ui/repo.yml, sequent-ui/templates/SequentConfig.js
Parent issue: https://github.com/sequentech/epi/issues/19
=> ✨ Countdown until logout

sequent-ui/templates/SequentConfig.js
Parent issue: https://github.com/sequentech/meta/issues/137
=> 🐞Fix ui deployment

config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel/sequent.config.yml, oneserver/templates/nginx.conf, sequent-ui/templates/SequentConfig.js
Parent issue: https://github.com/sequentech/meta/issues/119
=> 🐞 add census data second batch will not be executed (#342)

ballot-box/templates/application.local.conf, config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel/sequent.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml, eorchestra/templates/base_settings.py, iam/templates/deploy.py, iam/templates/test_settings.py, sequent-ui/templates/SequentConfig.js
Parent issue: https://github.com/sequentech/meta/issues/146
=> ✨ Enable progressive tallies

config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel/sequent.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
Parent issue: https://github.com/sequentech/meta/issues/235
=> Add italian language support

packages.yml, sequent-ui/templates/install_node.sh
Parent issue: https://github.com/sequentech/meta/issues/304
=> 🐞 Fix nodejs installation

packages.yml, sequent-ui/templates/install_node.sh
Parent issue: https://github.com/sequentech/meta/issues/304
=> 🐞 Fix nodejs installation (#346)

config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel/sequent.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml, iam/templates/deploy.py, sequent-ui/templates/SequentConfig.js
Parent issue: https://github.com/sequentech/meta/issues/256
=> ✨ Refresh & document OIDC support

config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel/sequent.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
Parent issue: https://github.com/sequentech/meta/issues/315
=> 🐞 default translation appears when switching language for the first time

config.yml, doc/devel/auth1.config.yml, doc/devel/auth2.config.yml, doc/devel/sequent.config.yml, doc/production/config.auth.yml, doc/production/config.master.yml
Parent issue: https://github.com/sequentech/meta/issues/315
=> 🐞 default translation appears when switching language for the first time (#352)

ballot-box/templates/ballot-box.conf, eorchestra/templates/election-orchestra.conf, iam/templates/supervisor_iam_celery.conf, iam/templates/supervisor_iam_celery_beat.conf
Parent issue: https://github.com/sequentech/meta/issues/912
=> 🐞 Logs are being deleted when services are restarted

iam/templates/deploy.py, iam/templates/test_settings.py, oneserver/templates/nginx.conf
Parent issue: https://github.com/sequentech/meta/issues/752
=> ✨🐞 Improve/rethink/fix Live Preview

ballot-box/templates/application.local.conf, ballot-box/templates/test.local.conf
Parent issue: https://github.com/sequentech/meta/issues/762
=> ✨ Separation of voting session time and bearer token lifetime
